name: speakmatch_v2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core utilities package
  url_launcher: ^6.0.17
  permission_handler: ^8.2.6
  wakelock: ^0.5.6
  share_plus: ^3.0.4
  # database package
  shared_preferences: ^2.0.9
  # voice call package
  agora_rtc_engine: ^4.0.7
  # network package
  dio: ^4.0.1
  # auth firebase packages
  firebase_auth: ^3.1.3
  google_sign_in: ^5.1.1
  # firebase packages
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.5
  firebase_messaging: ^11.2.0
  # presentation packages
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  avatar_glow: ^2.0.1
  flutter_easyloading: ^3.0.3
  shimmer: ^2.0.0
  image_picker: ^0.8.4+3
  lottie: ^1.2.1
  circular_countdown_timer: ^0.2.0
  # state management package
  flutter_bloc: ^7.3.3
  get: ^4.3.8
  # purchase package
  in_app_purchase: ^2.0.0
  # google ads package
  google_mobile_ads: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/
    